# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for Amplifier

This file was auto-generated by rvoxgen.
"""


class BaseAmplifier:
    name = "Amplifier"
    mtype = "Amplifier"
    mgroup = "Effect"
