# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for Compressor

This file was auto-generated by rvoxgen.
"""
from enum import Enum

from rv.controller import Controller


class BaseCompressor:
    name = "Compressor"
    mtype = "Compressor"
    mgroup = "Effect"

    class Mode(Enum):
        peak = 0
        rms = 1
        peak_zero_latency = 2

    volume = Controller((0, 512), 256)
    threshold = Controller((0, 512), 256)
    slope_pct = Controller((0, 200), 100)
    attack_ms = Controller((0, 500), 1)
    release_ms = Controller((1, 1000), 300)
    mode = Controller(Mode, Mode.peak)
    sidechain_input = Controller((0, 32), 0)
