# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for Compressor

This file was auto-generated by rvoxgen.
"""
from enum import Enum


class BaseCompressor:
    name = "Compressor"
    mtype = "Compressor"
    mgroup = "Effect"

    class Mode(Enum):
        peak = 0
        rms = 1
        peak_zero_latency = 2
