# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for Eq

This file was auto-generated by rvoxgen.
"""
from enum import Enum


class BaseEq:
    name = "Eq"
    mtype = "EQ"
    mgroup = "Effect"

    class Channels(Enum):
        stereo = 0
        mono = 1
