# This file was auto-generated by rvoxgen.
# -- DO NOT EDIT DIRECTLY --

from enum import Enum


class BaseFeedback:
    name = "Feedback"
    mtype = "Feedback"
    mgroup = "Misc"

    class Channels(Enum):
        stereo = 0
        mono = 1
