# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for Fm

This file was auto-generated by rvoxgen.
"""
from enum import Enum


class BaseFm:
    name = "Fm"
    mtype = "FM"
    mgroup = "Synth"

    class Mode(Enum):
        hq = 0
        hq_mono = 1
        lq = 2
        lq_mono = 3
