# This file was auto-generated by rvoxgen.
# -- DO NOT EDIT DIRECTLY --


from enum import Enum


class BaseInput:
    name = "Input"
    mtype = "Input"
    mgroup = "Synth"

    class Channels(Enum):
        mono = 0
        stereo = 1
