# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for MetaModule
This file was auto-generated by rvoxgen.
"""
from enum import Enum

from rv.controller import Controller
from rv.option import Option


class BaseMetaModule:
    name = "MetaModule"
    mtype = "MetaModule"
    mgroup = "Misc"

    class PlayPatterns(Enum):
        off = 0
        on = 1
        on_no_repeat = 2

    volume = Controller((0, 1024), 256)
    input_module = Controller((1, 256), 1)
    play_patterns = Controller(PlayPatterns, PlayPatterns.off)
    bpm = Controller((1, 800), 125)
    tpl = Controller((1, 31), 6)
    user_defined_controllers = Option(0, (0, 27))
    arpeggiator = Option(False)
    apply_velocity_to_project = Option(False)
    event_output = Option(True, inverted=True)
