# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for MultiSynth
This file was auto-generated by rvoxgen.
"""
from rv.controller import CompactRange, Controller
from rv.option import Option


class BaseMultiSynth:
    name = "MultiSynth"
    mtype = "MultiSynth"
    mgroup = "Misc"
    transpose = Controller(CompactRange(-128, 128), 0)
    random_pitch = Controller((0, 4096), 0)
    velocity = Controller((0, 256), 256)
    finetune = Controller((-256, 256), 0)
    random_phase = Controller((0, 32768), 0)
    random_velocity = Controller((0, 32768), 0)
    phase = Controller((0, 32768), 0)
    curve2_influence = Controller((0, 256), 256)
    use_static_note_C5 = Option(False)
    ignore_notes_with_zero_velocity = Option(False)
    vv_curve_active = Option(False)
    trigger = Option(False)
