# This file was auto-generated by rvoxgen.
# -- DO NOT EDIT DIRECTLY --

from rv.option import Option


class BaseMultiSynth:
    name = "MultiSynth"
    mtype = "MultiSynth"
    mgroup = "Misc"

    use_static_note_C5 = Option(False)
    ignore_notes_with_zero_velocity = Option(False)
    vv_curve_active = Option(False)
    trigger = Option(False)
