# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for MultiCtl

This file was auto-generated by rvoxgen.
"""


class BaseMultiCtl:
    name = "MultiCtl"
    mtype = "MultiCtl"
    mgroup = "Misc"
