# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for Reverb

This file was auto-generated by rvoxgen.
"""
from enum import Enum


class BaseReverb:
    name = "Reverb"
    mtype = "Reverb"
    mgroup = "Effect"

    class Mode(Enum):
        hq = 0
        hq_mono = 1
        lq = 2
        lq_mono = 3
