# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for VocalFilter

This file was auto-generated by rvoxgen.
"""
from enum import Enum


class BaseVocalFilter:
    name = "VocalFilter"
    mtype = "Vocal filter"
    mgroup = "Effect"

    class VoiceType(Enum):
        soprano = 0
        alto = 1
        tenor = 2
        bass = 3

    class Channels(Enum):
        stereo = 0
        mono = 1
