# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for VorbisPlayer

This file was auto-generated by rvoxgen.
"""
from rv.controller import Controller


class BaseVorbisPlayer:
    name = "VorbisPlayer"
    mtype = "Vorbis player"
    mgroup = "Synth"

    volume = Controller((0, 512), 256)
    original_speed = Controller(bool, True)
    finetune = Controller((-128, 128), 0)
    transpose = Controller((-128, 128), 0)
    interpolation = Controller(bool, True)
    polyphony_ch = Controller((1, 4), 1)
    repeat = Controller(bool, False)
