# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for VorbisPlayer

This file was auto-generated by rvoxgen.
"""


class BaseVorbisPlayer:
    name = "VorbisPlayer"
    mtype = "Vorbis player"
    mgroup = "Synth"
