# This file was auto-generated by rvoxgen.
# -- DO NOT EDIT DIRECTLY --


from enum import Enum


class BaseWaveShaper:
    name = "WaveShaper"
    mtype = "WaveShaper"
    mgroup = "Effect"

    class Mode(Enum):
        hq = 0
        hq_mono = 1
        lq = 2
        lq_mono = 3
