version: 2
sphinx:
  configuration: docs/conf.py
formats: []
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
