# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for Ctl2Note
This file was auto-generated by genrv.
"""
from enum import IntEnum

from rv.controller import Controller


class BaseCtl2Note:
    name = "Ctl2Note"
    mtype = "Ctl2Note"
    mgroup = "Misc"
    flags = 25301057

    class NoteOn(IntEnum):
        no_trigger = 0
        on_pitch_change = 1

    class NoteOff(IntEnum):
        no_trigger = 0
        on_min_pitch = 1
        on_max_pitch = 2

    pitch = Controller((0, 32768), 0)
    first_note = Controller((0, 120), 0)
    range_semitones = Controller((0, 120), 120)
    transpose = Controller((-128, 128), 0)
    finetune = Controller((-256, 256), 0)
    velocity = Controller((0, 256), 256)
    state = Controller(bool, False)
    note_on = Controller(NoteOn, NoteOn.on_pitch_change)
    note_off = Controller(NoteOff, NoteOff.on_min_pitch)
    record_notes = Controller(bool, False)
