# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for DrumSynth
This file was auto-generated by genrv.
"""
from rv.controller import Controller


class BaseDrumSynth:
    name = "DrumSynth"
    mtype = "DrumSynth"
    mgroup = "Synth"
    flags = 73
    volume = Controller((0, 512), 256)
    panning = Controller((-128, 128), 0)
    polyphony_ch = Controller((1, 8), 4)
    bass_volume = Controller((0, 512), 200)
    bass_power = Controller((0, 256), 256)
    bass_tone = Controller((0, 256), 64)
    bass_length = Controller((0, 256), 64)
    hihat_volume = Controller((0, 512), 256)
    hihat_length = Controller((0, 256), 64)
    snare_volume = Controller((0, 512), 256)
    snare_tone = Controller((0, 256), 128)
    snare_length = Controller((0, 256), 64)
    bass_panning = Controller((-128, 128), 0)
    hihat_panning = Controller((-128, 128), 0)
    snare_panning = Controller((-128, 128), 0)
