# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for Flanger
This file was auto-generated by genrv.
"""
from enum import IntEnum

from rv.controller import Controller


class BaseFlanger:
    name = "Flanger"
    mtype = "Flanger"
    mgroup = "Effect"
    flags = 1105

    class LfoWaveform(IntEnum):
        hsin = 0
        sin = 1

    class LfoFreqUnit(IntEnum):
        hz_0_05 = 0
        ms = 1
        hz = 2
        tick = 3
        line = 4
        line_2 = 5
        line_3 = 6

    dry = Controller((0, 256), 256)
    wet = Controller((0, 256), 128)
    feedback = Controller((0, 256), 128)
    delay = Controller((0, 1000), 200)
    response = Controller((0, 256), 2)
    lfo_freq = Controller((0, 512), 8)
    lfo_amp = Controller((0, 256), 32)
    lfo_waveform = Controller(LfoWaveform, LfoWaveform.hsin)
    set_lfo_phase = Controller((0, 256), 0)
    lfo_freq_unit = Controller(LfoFreqUnit, LfoFreqUnit.hz_0_05)
