# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for Input
This file was auto-generated by genrv.
"""
from enum import Enum

from rv.controller import Controller


class BaseInput:
    name = "Input"
    mtype = "Input"
    mgroup = "Synth"
    flags = 73

    class Channels(Enum):
        mono = 0
        stereo = 1

    volume = Controller((0, 1024), 256)
    channels = Controller(Channels, Channels.mono)
