# -- DO NOT EDIT THIS FILE DIRECTLY --
"""
Base class for Reverb
This file was auto-generated by genrv.
"""
from enum import IntEnum

from rv.controller import Controller


class BaseReverb:
    name = "Reverb"
    mtype = "Reverb"
    mgroup = "Effect"
    flags = 0x51

    class Mode(IntEnum):
        hq = 0
        hq_mono = 1
        lq = 2
        lq_mono = 3

    class AllPassFilter(IntEnum):
        off = 0
        on = 1
        on_improved = 2

    dry = Controller((0, 256), 256)
    wet = Controller((0, 256), 40)
    feedback = Controller((0, 256), 256)
    damp = Controller((0, 256), 128)
    stereo_width = Controller((0, 256), 256)
    freeze = Controller(bool, False)
    mode = Controller(Mode, Mode.hq)
    all_pass_filter = Controller(AllPassFilter, AllPassFilter.on)
    room_size = Controller((0, 128), 16)
    random_seed = Controller((0, 32768), 0)
