/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
export interface AmplifierControllerValues extends ControllerValues {
  volume: number
  balance: number
  dcOffset: number
  inverse: boolean
  stereoWidth: number
  absolute: boolean
  fineVolume: number
  gain: number
  bipolarDcOffset: number
}
