/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
// @ts-ignore
// noinspection ES6UnusedImports
import { Mode } from "./analogGeneratorEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { Waveform } from "./analogGeneratorEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { Filter } from "./analogGeneratorEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { FilterEnvelope } from "./analogGeneratorEnums"
export interface AnalogGeneratorControllerValues extends ControllerValues {
  volume: number
  waveform: Waveform
  panning: number
  attack: number
  release: number
  sustain: boolean
  exponentialEnvelope: boolean
  dutyCycle: number
  freq2: number
  filter: Filter
  fFreqHz: number
  fResonance: number
  fExponentialFreq: boolean
  fAttack: number
  fRelease: number
  fEnvelope: FilterEnvelope
  polyphonyCh: number
  mode: Mode
  noise: number
}
