/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
// Intentionally duplicated enums - see also analogGenerator.ts
// (TypeScript does not allow exporting imported enums from inside a namespace)
export enum Mode {
  // noinspection JSUnusedGlobalSymbols
  Hq = 0,
  HqMono = 1,
  Lq = 2,
  LqMono = 3,
}
export enum Waveform {
  // noinspection JSUnusedGlobalSymbols
  Triangle = 0,
  Saw = 1,
  Square = 2,
  Noise = 3,
  Drawn = 4,
  Sin = 5,
  Hsin = 6,
  Asin = 7,
  DrawnSpline = 8,
  NoiseSpline = 9,
  WhiteNoise = 10,
  PinkNoise = 11,
  RedNoise = 12,
  BlueNoise = 13,
  VioletNoise = 14,
  GreyNoise = 15,
  Harmonics = 16,
}
export enum Filter {
  // noinspection JSUnusedGlobalSymbols
  Off = 0,
  Lp_12dB = 1,
  Hp_12dB = 2,
  Bp_12dB = 3,
  Br_12dB = 4,
  Lp_24dB = 5,
  Hp_24dB = 6,
  Bp_24dB = 7,
  Br_24dB = 8,
}
export enum FilterEnvelope {
  // noinspection JSUnusedGlobalSymbols
  Off = 0,
  SustainOff = 1,
  SustainOn = 2,
}
export enum Osc2Mode {
  // noinspection JSUnusedGlobalSymbols
  Add = 0,
  Sub = 1,
  Mul = 2,
  Min = 3,
  Max = 4,
  BitwiseAnd = 5,
  BitwiseXor = 6,
}
