/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
export interface CompressorControllerValues extends ControllerValues {
  volume: number
  threshold: number
  slopePct: number
  attackMs: number
  releaseMs: number
  mode: Mode
  sidechainInput: number
}
