/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
export enum Mode {
  // noinspection JSUnusedGlobalSymbols
  Peak = 0,
  Rms = 1,
  PeakZeroLatency = 2,
}
