/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
// @ts-ignore
// noinspection ES6UnusedImports
import { Channels } from "./dcBlockerEnums"
export interface DcBlockerControllerValues extends ControllerValues {
  channels: Channels
}
