/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { Controllers } from "./moduleType"
import { DcBlockerControllerValues } from "./dcBlockerControllerValues"
// @ts-ignore
// noinspection ES6UnusedImports
import { Channels } from "./dcBlockerEnums"
export class DcBlockerBaseControllers implements Controllers {
  constructor(readonly controllerValues: DcBlockerControllerValues) {}
  // noinspection JSUnusedGlobalSymbols
  get channels(): Channels {
    return this.controllerValues.channels
  }
  // noinspection JSUnusedGlobalSymbols
  set channels(newValue: Channels) {
    const { controllerValues } = this
    controllerValues.channels = newValue
  }
}
