/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
export enum Type {
  // noinspection JSUnusedGlobalSymbols
  Lim = 0,
  Clipping = 0,
  Sat = 1,
  Foldback = 1,
  Foldback2 = 2,
  Foldback3 = 3,
  Overflow = 4,
}
