/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
export interface DrumSynthControllerValues extends ControllerValues {
  volume: number
  panning: number
  polyphony: number
  bassVolume: number
  bassPower: number
  bassTone: number
  bassLength: number
  hihatVolume: number
  hihatLength: number
  snareVolume: number
  snareTone: number
  snareLength: number
  bassPanning: number
  hihatPanning: number
  snarePanning: number
}
