/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { MidiMap, ControllerMidiMap, ControllerMidiMaps } from "../controllerMidiMap"
import { Project } from "../project"
import { ModuleBase } from "./moduleBase"
import { ModuleType, OptionValues, Options } from "./moduleType"
import { EchoBehavior } from "./echoBehavior"
import { EchoControllers } from "./echoControllers"
import { EchoControllerValues } from "./echoControllerValues"
export namespace Echo {
  // Intentionally duplicated enums - see also echoEnums.ts
  // (TypeScript does not allow exporting imported enums from inside a namespace)
  export enum Channels {
    // noinspection JSUnusedGlobalSymbols
    Mono = 0,
    Stereo = 1,
  }
  export enum DelayUnit {
    // noinspection JSUnusedGlobalSymbols
    Sec_256 = 0,
    Ms = 1,
    Hz = 2,
    Tick = 3,
    Line = 4,
    Line_2 = 5,
    Line_3 = 6,
  }
  export enum CtlNum {
    Dry = 1,
    Wet = 2,
    Feedback = 3,
    Delay = 4,
    Channels = 5,
    DelayUnit = 6,
  }
  interface EchoControllerMidiMaps extends ControllerMidiMaps {
    dry: ControllerMidiMap
    wet: ControllerMidiMap
    feedback: ControllerMidiMap
    delay: ControllerMidiMap
    channels: ControllerMidiMap
    delayUnit: ControllerMidiMap
  }
  interface EchoOptionValues extends OptionValues {}
  class EchoOptions implements Options {
    constructor(readonly optionValues: EchoOptionValues) {}
  }
  export class Module extends ModuleBase implements ModuleType {
    name = "Echo"
    flags = 1105
    readonly typeName = "Echo"
    readonly controllerSetters = [
      (val: number) => {
        this.controllerValues.dry = val
      },
      (val: number) => {
        this.controllerValues.wet = val
      },
      (val: number) => {
        this.controllerValues.feedback = val
      },
      (val: number) => {
        this.controllerValues.delay = val
      },
      (val: number) => {
        this.controllerValues.channels = val
      },
      (val: number) => {
        this.controllerValues.delayUnit = val
      },
    ]
    readonly controllerValues: EchoControllerValues = {
      dry: 256,
      wet: 128,
      feedback: 128,
      delay: 256,
      channels: Channels.Stereo,
      delayUnit: DelayUnit.Sec_256,
    }
    readonly controllers: EchoControllers = new EchoControllers(
      this,
      this.controllerValues
    )
    readonly c = this.controllers
    readonly midiMaps: EchoControllerMidiMaps = {
      dry: new ControllerMidiMap(),
      wet: new ControllerMidiMap(),
      feedback: new ControllerMidiMap(),
      delay: new ControllerMidiMap(),
      channels: new ControllerMidiMap(),
      delayUnit: new ControllerMidiMap(),
    }
    readonly optionValues: EchoOptionValues = {}
    readonly options: EchoOptions = new EchoOptions(this.optionValues)
    readonly o = this.options
    behavior?: EchoBehavior
    constructor() {
      super()
      this.behavior = new EchoBehavior(this)
    }
    attachTo(project: Project): AttachedModule {
      return super.attachTo(project) as AttachedModule
    }
    setRawControllerValue(ctlNum: number, value: number) {
      const { controllerValues: cv } = this
      switch (ctlNum) {
        case 1:
          cv.dry = value
          break
        case 2:
          cv.wet = value
          break
        case 3:
          cv.feedback = value
          break
        case 4:
          cv.delay = value
          break
        case 5:
          cv.channels = value
          break
        case 6:
          cv.delayUnit = value
          break
      }
    }
    *rawControllerValues(): Generator<number> {
      const { controllerValues: cv } = this
      yield cv.dry
      yield cv.wet
      yield cv.feedback
      yield cv.delay
      yield cv.channels
      yield cv.delayUnit
    }
    setMidiMaps(midiMaps: MidiMap[]) {
      this.midiMaps.dry = midiMaps[0] || {
        channel: 0,
        messageType: 0,
        messageParameter: 0,
        slope: 0,
      }
      this.midiMaps.wet = midiMaps[1] || {
        channel: 0,
        messageType: 0,
        messageParameter: 0,
        slope: 0,
      }
      this.midiMaps.feedback = midiMaps[2] || {
        channel: 0,
        messageType: 0,
        messageParameter: 0,
        slope: 0,
      }
      this.midiMaps.delay = midiMaps[3] || {
        channel: 0,
        messageType: 0,
        messageParameter: 0,
        slope: 0,
      }
      this.midiMaps.channels = midiMaps[4] || {
        channel: 0,
        messageType: 0,
        messageParameter: 0,
        slope: 0,
      }
      this.midiMaps.delayUnit = midiMaps[5] || {
        channel: 0,
        messageType: 0,
        messageParameter: 0,
        slope: 0,
      }
    }
    midiMapsArray(): MidiMap[] {
      const a: MidiMap[] = []
      a.push(this.midiMaps.dry)
      a.push(this.midiMaps.wet)
      a.push(this.midiMaps.feedback)
      a.push(this.midiMaps.delay)
      a.push(this.midiMaps.channels)
      a.push(this.midiMaps.delayUnit)
      return a
    }
  }
  export class AttachedModule extends Module {
    get index(): number {
      if (this._index === undefined) {
        throw new Error("Attached module has empty index")
      }
      return this._index
    }
    set index(_: number) {
      throw new Error("Module index can only be assigned once")
    }
  }
}
