/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { MidiMap, ControllerMidiMap, ControllerMidiMaps } from "../controllerMidiMap"
import { Project } from "../project"
import { ModuleBase } from "./moduleBase"
import {
  ControllerValues,
  Controllers,
  ModuleType,
  OptionValues,
  Options,
} from "./moduleType"
import { FeedbackBehavior } from "./feedbackBehavior"
export namespace Feedback {
  export const enum Channels {
    // noinspection JSUnusedGlobalSymbols
    Stereo = 0,
    Mono = 1,
  }
  interface FeedbackControllerValues extends ControllerValues {
    volume: number
    channels: Channels
  }
  class FeedbackControllers implements Controllers {
    constructor(readonly controllerValues: FeedbackControllerValues) {}
    // noinspection JSUnusedGlobalSymbols
    get volume(): number {
      return this.controllerValues.volume
    }
    // noinspection JSUnusedGlobalSymbols
    set volume(newValue: number) {
      const { controllerValues } = this
      newValue = Math.min(Math.max(newValue, 0), 10000)
      controllerValues.volume = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get channels(): Channels {
      return this.controllerValues.channels
    }
    // noinspection JSUnusedGlobalSymbols
    set channels(newValue: Channels) {
      const { controllerValues } = this
      controllerValues.channels = newValue
    }
  }
  interface FeedbackControllerMidiMaps extends ControllerMidiMaps {
    volume: ControllerMidiMap
    channels: ControllerMidiMap
  }
  interface FeedbackOptionValues extends OptionValues {}
  class FeedbackOptions implements Options {
    constructor(readonly optionValues: FeedbackOptionValues) {}
  }
  export class Module extends ModuleBase implements ModuleType {
    name = "Feedback"
    flags = 6291537
    readonly typeName = "Feedback"
    readonly controllerSetters = [
      (val: number) => {
        this.controllerValues.volume = val
      },
      (val: number) => {
        this.controllerValues.channels = val
      },
    ]
    readonly controllerValues: FeedbackControllerValues = {
      volume: 1000,
      channels: Channels.Stereo,
    }
    readonly controllers: FeedbackControllers = new FeedbackControllers(
      this.controllerValues
    )
    readonly c = this.controllers
    readonly midiMaps: FeedbackControllerMidiMaps = {
      volume: new ControllerMidiMap(),
      channels: new ControllerMidiMap(),
    }
    readonly optionValues: FeedbackOptionValues = {}
    readonly options: FeedbackOptions = new FeedbackOptions(this.optionValues)
    readonly o = this.options
    behavior?: FeedbackBehavior
    constructor() {
      super()
      this.behavior = new FeedbackBehavior(this)
    }
    attachTo(project: Project): AttachedModule {
      return super.attachTo(project) as AttachedModule
    }
    *rawControllerValues(): Generator<number> {
      const { controllerValues: cv } = this
      yield cv.volume
      yield cv.channels
    }
    setMidiMaps(midiMaps: MidiMap[]) {
      this.midiMaps.volume = midiMaps[0]
      this.midiMaps.channels = midiMaps[1]
    }
    midiMapsArray(): MidiMap[] {
      const a: MidiMap[] = []
      a.push(this.midiMaps.volume)
      a.push(this.midiMaps.channels)
      return a
    }
  }
  export class AttachedModule extends Module {
    get index(): number {
      if (this._index === undefined) {
        throw new Error("Attached module has empty index")
      }
      return this._index
    }
    set index(_: number) {
      throw new Error("Module index can only be assigned once")
    }
  }
}
