/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
// Intentionally duplicated enums - see also fft.ts
// (TypeScript does not allow exporting imported enums from inside a namespace)
export enum SampleRate {
  // noinspection JSUnusedGlobalSymbols
  _8000Hz = 0,
  _11025Hz = 1,
  _16000Hz = 2,
  _22050Hz = 3,
  _32000Hz = 4,
  _44100Hz = 5,
  _48000Hz = 6,
  _88200Hz = 7,
  _96000Hz = 8,
  _119200Hz = 9,
}
export enum Channels {
  // noinspection JSUnusedGlobalSymbols
  Mono = 0,
  Stereo = 1,
}
export enum Buffer {
  // noinspection JSUnusedGlobalSymbols
  _64 = 0,
  _128 = 1,
  _256 = 2,
  _512 = 3,
  _1024 = 4,
  _2048 = 5,
  _4096 = 6,
  _8192 = 7,
}
export enum BufferOverlap {
  // noinspection JSUnusedGlobalSymbols
  _0 = 0,
  _2x = 1,
  _4x = 2,
}
