/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
// @ts-ignore
// noinspection ES6UnusedImports
import { Type } from "./filterProEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { RollOff } from "./filterProEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { Mode } from "./filterProEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { LfoWaveform } from "./filterProEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { LfoFreqUnit } from "./filterProEnums"
export interface FilterProControllerValues extends ControllerValues {
  volume: number
  type: Type
  freqHz: number
  freqFinetune: number
  freqScale: number
  exponentialFreq: boolean
  q: number
  gain: number
  rollOff: RollOff
  response: number
  mode: Mode
  mix: number
  lfoFreq: number
  lfoAmp: number
  lfoWaveform: LfoWaveform
  setLfoPhase: number
  lfoFreqUnit: LfoFreqUnit
}
