/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { Controllers, ModuleType } from "./moduleType"
import { FilterControllerValues } from "./filterControllerValues"
// @ts-ignore
// noinspection ES6UnusedImports
import { Type } from "./filterEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { Mode } from "./filterEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { RollOff } from "./filterEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { LfoFreqUnit } from "./filterEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { LfoWaveform } from "./filterEnums"
export class FilterBaseControllers implements Controllers {
  constructor(
    readonly module: ModuleType,
    readonly controllerValues: FilterControllerValues
  ) {}
  // noinspection JSUnusedGlobalSymbols
  get volume(): number {
    return this.controllerValues.volume
  }
  // noinspection JSUnusedGlobalSymbols
  set volume(newValue: number) {
    const { controllerValues } = this
    newValue = Math.min(Math.max(newValue, 0), 256)
    controllerValues.volume = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get freq(): number {
    return this.controllerValues.freq
  }
  // noinspection JSUnusedGlobalSymbols
  set freq(newValue: number) {
    const { controllerValues } = this
    newValue = Math.min(Math.max(newValue, 0), 14000)
    controllerValues.freq = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get resonance(): number {
    return this.controllerValues.resonance
  }
  // noinspection JSUnusedGlobalSymbols
  set resonance(newValue: number) {
    const { controllerValues } = this
    newValue = Math.min(Math.max(newValue, 0), 1530)
    controllerValues.resonance = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get type(): Type {
    return this.controllerValues.type
  }
  // noinspection JSUnusedGlobalSymbols
  set type(newValue: Type) {
    const { controllerValues } = this
    controllerValues.type = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get response(): number {
    return this.controllerValues.response
  }
  // noinspection JSUnusedGlobalSymbols
  set response(newValue: number) {
    const { controllerValues } = this
    newValue = Math.min(Math.max(newValue, 0), 256)
    controllerValues.response = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get mode(): Mode {
    return this.controllerValues.mode
  }
  // noinspection JSUnusedGlobalSymbols
  set mode(newValue: Mode) {
    const { controllerValues } = this
    controllerValues.mode = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get impulse(): number {
    return this.controllerValues.impulse
  }
  // noinspection JSUnusedGlobalSymbols
  set impulse(newValue: number) {
    const { controllerValues } = this
    newValue = Math.min(Math.max(newValue, 0), 14000)
    controllerValues.impulse = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get mix(): number {
    return this.controllerValues.mix
  }
  // noinspection JSUnusedGlobalSymbols
  set mix(newValue: number) {
    const { controllerValues } = this
    newValue = Math.min(Math.max(newValue, 0), 256)
    controllerValues.mix = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get lfoFreq(): number {
    return this.controllerValues.lfoFreq
  }
  // noinspection JSUnusedGlobalSymbols
  set lfoFreq(newValue: number) {
    const { controllerValues } = this
    newValue = Math.min(Math.max(newValue, 0), 1024)
    controllerValues.lfoFreq = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get lfoAmp(): number {
    return this.controllerValues.lfoAmp
  }
  // noinspection JSUnusedGlobalSymbols
  set lfoAmp(newValue: number) {
    const { controllerValues } = this
    newValue = Math.min(Math.max(newValue, 0), 256)
    controllerValues.lfoAmp = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get setLfoPhase(): number {
    return this.controllerValues.setLfoPhase
  }
  // noinspection JSUnusedGlobalSymbols
  set setLfoPhase(newValue: number) {
    const { controllerValues } = this
    newValue = Math.min(Math.max(newValue, 0), 256)
    controllerValues.setLfoPhase = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get exponentialFreq(): boolean {
    return this.controllerValues.exponentialFreq
  }
  // noinspection JSUnusedGlobalSymbols
  set exponentialFreq(newValue: boolean) {
    const { controllerValues } = this
    controllerValues.exponentialFreq = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get rollOff(): RollOff {
    return this.controllerValues.rollOff
  }
  // noinspection JSUnusedGlobalSymbols
  set rollOff(newValue: RollOff) {
    const { controllerValues } = this
    controllerValues.rollOff = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get lfoFreqUnit(): LfoFreqUnit {
    return this.controllerValues.lfoFreqUnit
  }
  // noinspection JSUnusedGlobalSymbols
  set lfoFreqUnit(newValue: LfoFreqUnit) {
    const { controllerValues } = this
    controllerValues.lfoFreqUnit = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get lfoWaveform(): LfoWaveform {
    return this.controllerValues.lfoWaveform
  }
  // noinspection JSUnusedGlobalSymbols
  set lfoWaveform(newValue: LfoWaveform) {
    const { controllerValues } = this
    controllerValues.lfoWaveform = newValue
  }
}
