/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { MidiMap, ControllerMidiMap, ControllerMidiMaps } from "../controllerMidiMap"
import { ModuleBase } from "./moduleBase"
import {
  ControllerValues,
  Controllers,
  ModuleType,
  OptionValues,
  Options,
} from "./moduleType"
import { FlangerBehavior } from "./flangerBehavior"
export namespace Flanger {
  export const enum LfoWaveform {
    // noinspection JSUnusedGlobalSymbols
    Hsin = 0,
    Sin = 1,
  }
  export const enum LfoFreqUnit {
    // noinspection JSUnusedGlobalSymbols
    Hz_0_05 = 0,
    Ms = 1,
    Hz = 2,
    Tick = 3,
    Line = 4,
    Line_2 = 5,
    Line_3 = 6,
  }
  interface FlangerControllerValues extends ControllerValues {
    dry: number
    wet: number
    feedback: number
    delay: number
    response: number
    lfoFreq: number
    lfoAmp: number
    lfoWaveform: LfoWaveform
    setLfoPhase: number
    lfoFreqUnit: LfoFreqUnit
  }
  class FlangerControllers implements Controllers {
    constructor(readonly controllerValues: FlangerControllerValues) {}
    // noinspection JSUnusedGlobalSymbols
    get dry(): number {
      return this.controllerValues.dry
    }
    // noinspection JSUnusedGlobalSymbols
    set dry(newValue: number) {
      const { controllerValues } = this
      newValue = Math.min(Math.max(newValue, 0), 256)
      controllerValues.dry = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get wet(): number {
      return this.controllerValues.wet
    }
    // noinspection JSUnusedGlobalSymbols
    set wet(newValue: number) {
      const { controllerValues } = this
      newValue = Math.min(Math.max(newValue, 0), 256)
      controllerValues.wet = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get feedback(): number {
      return this.controllerValues.feedback
    }
    // noinspection JSUnusedGlobalSymbols
    set feedback(newValue: number) {
      const { controllerValues } = this
      newValue = Math.min(Math.max(newValue, 0), 256)
      controllerValues.feedback = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get delay(): number {
      return this.controllerValues.delay
    }
    // noinspection JSUnusedGlobalSymbols
    set delay(newValue: number) {
      const { controllerValues } = this
      newValue = Math.min(Math.max(newValue, 0), 1000)
      controllerValues.delay = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get response(): number {
      return this.controllerValues.response
    }
    // noinspection JSUnusedGlobalSymbols
    set response(newValue: number) {
      const { controllerValues } = this
      newValue = Math.min(Math.max(newValue, 0), 256)
      controllerValues.response = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get lfoFreq(): number {
      return this.controllerValues.lfoFreq
    }
    // noinspection JSUnusedGlobalSymbols
    set lfoFreq(newValue: number) {
      const { controllerValues } = this
      newValue = Math.min(Math.max(newValue, 0), 512)
      controllerValues.lfoFreq = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get lfoAmp(): number {
      return this.controllerValues.lfoAmp
    }
    // noinspection JSUnusedGlobalSymbols
    set lfoAmp(newValue: number) {
      const { controllerValues } = this
      newValue = Math.min(Math.max(newValue, 0), 256)
      controllerValues.lfoAmp = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get lfoWaveform(): LfoWaveform {
      return this.controllerValues.lfoWaveform
    }
    // noinspection JSUnusedGlobalSymbols
    set lfoWaveform(newValue: LfoWaveform) {
      const { controllerValues } = this
      controllerValues.lfoWaveform = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get setLfoPhase(): number {
      return this.controllerValues.setLfoPhase
    }
    // noinspection JSUnusedGlobalSymbols
    set setLfoPhase(newValue: number) {
      const { controllerValues } = this
      newValue = Math.min(Math.max(newValue, 0), 256)
      controllerValues.setLfoPhase = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get lfoFreqUnit(): LfoFreqUnit {
      return this.controllerValues.lfoFreqUnit
    }
    // noinspection JSUnusedGlobalSymbols
    set lfoFreqUnit(newValue: LfoFreqUnit) {
      const { controllerValues } = this
      controllerValues.lfoFreqUnit = newValue
    }
  }
  interface FlangerControllerMidiMaps extends ControllerMidiMaps {
    dry: ControllerMidiMap
    wet: ControllerMidiMap
    feedback: ControllerMidiMap
    delay: ControllerMidiMap
    response: ControllerMidiMap
    lfoFreq: ControllerMidiMap
    lfoAmp: ControllerMidiMap
    lfoWaveform: ControllerMidiMap
    setLfoPhase: ControllerMidiMap
    lfoFreqUnit: ControllerMidiMap
  }
  interface FlangerOptionValues extends OptionValues {}
  class FlangerOptions implements Options {
    constructor(readonly optionValues: FlangerOptionValues) {}
  }
  export class Module extends ModuleBase implements ModuleType {
    name = "Flanger"
    flags = 0
    readonly typeName = "Flanger"
    readonly controllerSetters = [
      (val: number) => {
        this.controllerValues.dry = val
      },
      (val: number) => {
        this.controllerValues.wet = val
      },
      (val: number) => {
        this.controllerValues.feedback = val
      },
      (val: number) => {
        this.controllerValues.delay = val
      },
      (val: number) => {
        this.controllerValues.response = val
      },
      (val: number) => {
        this.controllerValues.lfoFreq = val
      },
      (val: number) => {
        this.controllerValues.lfoAmp = val
      },
      (val: number) => {
        this.controllerValues.lfoWaveform = val
      },
      (val: number) => {
        this.controllerValues.setLfoPhase = val
      },
      (val: number) => {
        this.controllerValues.lfoFreqUnit = val
      },
    ]
    readonly controllerValues: FlangerControllerValues = {
      dry: 256,
      wet: 128,
      feedback: 128,
      delay: 200,
      response: 2,
      lfoFreq: 8,
      lfoAmp: 32,
      lfoWaveform: LfoWaveform.Hsin,
      setLfoPhase: 0,
      lfoFreqUnit: LfoFreqUnit.Hz_0_05,
    }
    readonly controllers: FlangerControllers = new FlangerControllers(
      this.controllerValues
    )
    readonly c = this.controllers
    readonly midiMaps: FlangerControllerMidiMaps = {
      dry: new ControllerMidiMap(),
      wet: new ControllerMidiMap(),
      feedback: new ControllerMidiMap(),
      delay: new ControllerMidiMap(),
      response: new ControllerMidiMap(),
      lfoFreq: new ControllerMidiMap(),
      lfoAmp: new ControllerMidiMap(),
      lfoWaveform: new ControllerMidiMap(),
      setLfoPhase: new ControllerMidiMap(),
      lfoFreqUnit: new ControllerMidiMap(),
    }
    readonly optionValues: FlangerOptionValues = {}
    readonly options: FlangerOptions = new FlangerOptions(this.optionValues)
    readonly o = this.options
    behavior?: FlangerBehavior
    constructor() {
      super()
      this.behavior = new FlangerBehavior(this)
    }
    *rawControllerValues(): Generator<number> {
      const { controllerValues: cv } = this
      yield cv.dry
      yield cv.wet
      yield cv.feedback
      yield cv.delay
      yield cv.response
      yield cv.lfoFreq
      yield cv.lfoAmp
      yield cv.lfoWaveform
      yield cv.setLfoPhase
      yield cv.lfoFreqUnit
    }
    setMidiMaps(midiMaps: MidiMap[]) {
      this.midiMaps.dry = midiMaps[0]
      this.midiMaps.wet = midiMaps[1]
      this.midiMaps.feedback = midiMaps[2]
      this.midiMaps.delay = midiMaps[3]
      this.midiMaps.response = midiMaps[4]
      this.midiMaps.lfoFreq = midiMaps[5]
      this.midiMaps.lfoAmp = midiMaps[6]
      this.midiMaps.lfoWaveform = midiMaps[7]
      this.midiMaps.setLfoPhase = midiMaps[8]
      this.midiMaps.lfoFreqUnit = midiMaps[9]
    }
    midiMapsArray(): MidiMap[] {
      const a: MidiMap[] = []
      a.push(this.midiMaps.dry)
      a.push(this.midiMaps.wet)
      a.push(this.midiMaps.feedback)
      a.push(this.midiMaps.delay)
      a.push(this.midiMaps.response)
      a.push(this.midiMaps.lfoFreq)
      a.push(this.midiMaps.lfoAmp)
      a.push(this.midiMaps.lfoWaveform)
      a.push(this.midiMaps.setLfoPhase)
      a.push(this.midiMaps.lfoFreqUnit)
      return a
    }
  }
}
