/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
// Intentionally duplicated enums - see also flanger.ts
// (TypeScript does not allow exporting imported enums from inside a namespace)
export enum LfoWaveform {
  // noinspection JSUnusedGlobalSymbols
  Hsin = 0,
  Sin = 1,
}
export enum LfoFreqUnit {
  // noinspection JSUnusedGlobalSymbols
  HzMul_0_05 = 0,
  Ms = 1,
  Hz = 2,
  Tick = 3,
  Line = 4,
  LineDiv_2 = 5,
  LineDiv_3 = 6,
}
