/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
// Intentionally duplicated enums - see also fm.ts
// (TypeScript does not allow exporting imported enums from inside a namespace)
export enum Mode {
  // noinspection JSUnusedGlobalSymbols
  Hq = 0,
  HqMono = 1,
  Lq = 2,
  LqMono = 3,
}
