/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
export interface GeneratorControllerValues extends ControllerValues {
  volume: number
  waveform: Waveform
  panning: number
  attack: number
  release: number
  polyphonyCh: number
  mode: Mode
  sustain: boolean
  freqModulationByInput: number
  dutyCycle: number
}
