/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
// Intentionally duplicated enums - see also generator.ts
// (TypeScript does not allow exporting imported enums from inside a namespace)
export enum Waveform {
  // noinspection JSUnusedGlobalSymbols
  Triangle = 0,
  Saw = 1,
  Square = 2,
  Noise = 3,
  Drawn = 4,
  Sin = 5,
  Hsin = 6,
  Asin = 7,
  Psin = 8,
}
export enum Mode {
  // noinspection JSUnusedGlobalSymbols
  Stereo = 0,
  Mono = 1,
}
