/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
export interface GlideControllerValues extends ControllerValues {
  response: number
  sampleRateHz: number
  resetOnFirstNote: boolean
  polyphony: boolean
  pitch: number
  pitchScale: number
  reset: boolean
}
