/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
// Intentionally duplicated enums - see also kicker.ts
// (TypeScript does not allow exporting imported enums from inside a namespace)
export enum Waveform {
  // noinspection JSUnusedGlobalSymbols
  Triangle = 0,
  Square = 1,
  Sin = 2,
}
