/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
export interface LfoControllerValues extends ControllerValues {
  volume: number
  type: Type
  amplitude: number
  freq: number
  waveform: Waveform
  setPhase: number
  channels: Channels
  frequencyUnit: FrequencyUnit
  dutyCycle: number
  generator: boolean
}
