/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
// @ts-ignore
// noinspection ES6UnusedImports
import { Type } from "./lfoEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { Waveform } from "./lfoEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { Channels } from "./lfoEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { FrequencyUnit } from "./lfoEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { SmoothTransitions } from "./lfoEnums"
export interface LfoControllerValues extends ControllerValues {
  volume: number
  type: Type
  amplitude: number
  freq: number
  waveform: Waveform
  setPhase: number
  channels: Channels
  frequencyUnit: FrequencyUnit
  dutyCycle: number
  generator: boolean
  freqScale: number
  smoothTransitions: SmoothTransitions
}
