/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
// Intentionally duplicated enums - see also lfo.ts
// (TypeScript does not allow exporting imported enums from inside a namespace)
export enum Type {
  // noinspection JSUnusedGlobalSymbols
  Amplitude = 0,
  Panning = 1,
}
export enum Waveform {
  // noinspection JSUnusedGlobalSymbols
  Sin = 0,
  Square = 1,
  Sin2 = 2,
  Saw = 3,
  Saw2 = 4,
  Random = 5,
  Triangle = 6,
  RandomInterpolated = 7,
}
export enum Channels {
  // noinspection JSUnusedGlobalSymbols
  Stereo = 0,
  Mono = 1,
}
export enum FrequencyUnit {
  // noinspection JSUnusedGlobalSymbols
  HzDiv_64 = 0,
  Ms = 1,
  Hz = 2,
  Tick = 3,
  Line = 4,
  LineDiv_2 = 5,
  LineDiv_3 = 6,
}
export enum SmoothTransitions {
  // noinspection JSUnusedGlobalSymbols
  Off = 0,
  Waveform = 1,
}
