/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
// Intentionally duplicated enums - see also loop.ts
// (TypeScript does not allow exporting imported enums from inside a namespace)
export enum Channels {
  // noinspection JSUnusedGlobalSymbols
  Mono = 0,
  Stereo = 1,
}
export enum Mode {
  // noinspection JSUnusedGlobalSymbols
  Normal = 0,
  PingPong = 1,
}
