/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { MidiMap, ControllerMidiMap, ControllerMidiMaps } from "../controllerMidiMap"
import { Project } from "../project"
import { ModuleBase } from "./moduleBase"
import {
  ControllerValues,
  Controllers,
  ModuleType,
  OptionValues,
  Options,
} from "./moduleType"
import { LoopBehavior } from "./loopBehavior"
export namespace Loop {
  export const enum Channels {
    // noinspection JSUnusedGlobalSymbols
    Mono = 0,
    Stereo = 1,
  }
  export const enum Mode {
    // noinspection JSUnusedGlobalSymbols
    Normal = 0,
    PingPong = 1,
  }
  interface LoopControllerValues extends ControllerValues {
    volume: number
    delay: number
    channels: Channels
    repeats: number
    mode: Mode
  }
  class LoopControllers implements Controllers {
    constructor(readonly controllerValues: LoopControllerValues) {}
    // noinspection JSUnusedGlobalSymbols
    get volume(): number {
      return this.controllerValues.volume
    }
    // noinspection JSUnusedGlobalSymbols
    set volume(newValue: number) {
      const { controllerValues } = this
      newValue = Math.min(Math.max(newValue, 0), 256)
      controllerValues.volume = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get delay(): number {
      return this.controllerValues.delay
    }
    // noinspection JSUnusedGlobalSymbols
    set delay(newValue: number) {
      const { controllerValues } = this
      newValue = Math.min(Math.max(newValue, 0), 256)
      controllerValues.delay = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get channels(): Channels {
      return this.controllerValues.channels
    }
    // noinspection JSUnusedGlobalSymbols
    set channels(newValue: Channels) {
      const { controllerValues } = this
      controllerValues.channels = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get repeats(): number {
      return this.controllerValues.repeats
    }
    // noinspection JSUnusedGlobalSymbols
    set repeats(newValue: number) {
      const { controllerValues } = this
      newValue = Math.min(Math.max(newValue, 0), 64)
      controllerValues.repeats = newValue
    }
    // noinspection JSUnusedGlobalSymbols
    get mode(): Mode {
      return this.controllerValues.mode
    }
    // noinspection JSUnusedGlobalSymbols
    set mode(newValue: Mode) {
      const { controllerValues } = this
      controllerValues.mode = newValue
    }
  }
  interface LoopControllerMidiMaps extends ControllerMidiMaps {
    volume: ControllerMidiMap
    delay: ControllerMidiMap
    channels: ControllerMidiMap
    repeats: ControllerMidiMap
    mode: ControllerMidiMap
  }
  interface LoopOptionValues extends OptionValues {}
  class LoopOptions implements Options {
    constructor(readonly optionValues: LoopOptionValues) {}
  }
  export class Module extends ModuleBase implements ModuleType {
    name = "Loop"
    flags = 1105
    readonly typeName = "Loop"
    readonly controllerSetters = [
      (val: number) => {
        this.controllerValues.volume = val
      },
      (val: number) => {
        this.controllerValues.delay = val
      },
      (val: number) => {
        this.controllerValues.channels = val
      },
      (val: number) => {
        this.controllerValues.repeats = val
      },
      (val: number) => {
        this.controllerValues.mode = val
      },
    ]
    readonly controllerValues: LoopControllerValues = {
      volume: 256,
      delay: 256,
      channels: Channels.Stereo,
      repeats: 0,
      mode: Mode.Normal,
    }
    readonly controllers: LoopControllers = new LoopControllers(this.controllerValues)
    readonly c = this.controllers
    readonly midiMaps: LoopControllerMidiMaps = {
      volume: new ControllerMidiMap(),
      delay: new ControllerMidiMap(),
      channels: new ControllerMidiMap(),
      repeats: new ControllerMidiMap(),
      mode: new ControllerMidiMap(),
    }
    readonly optionValues: LoopOptionValues = {}
    readonly options: LoopOptions = new LoopOptions(this.optionValues)
    readonly o = this.options
    behavior?: LoopBehavior
    constructor() {
      super()
      this.behavior = new LoopBehavior(this)
    }
    attachTo(project: Project): Module {
      return super.attachTo(project) as Module
    }
    *rawControllerValues(): Generator<number> {
      const { controllerValues: cv } = this
      yield cv.volume
      yield cv.delay
      yield cv.channels
      yield cv.repeats
      yield cv.mode
    }
    setMidiMaps(midiMaps: MidiMap[]) {
      this.midiMaps.volume = midiMaps[0]
      this.midiMaps.delay = midiMaps[1]
      this.midiMaps.channels = midiMaps[2]
      this.midiMaps.repeats = midiMaps[3]
      this.midiMaps.mode = midiMaps[4]
    }
    midiMapsArray(): MidiMap[] {
      const a: MidiMap[] = []
      a.push(this.midiMaps.volume)
      a.push(this.midiMaps.delay)
      a.push(this.midiMaps.channels)
      a.push(this.midiMaps.repeats)
      a.push(this.midiMaps.mode)
      return a
    }
  }
}
