/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
// Intentionally duplicated enums - see also loop.ts
// (TypeScript does not allow exporting imported enums from inside a namespace)
export enum Channels {
  // noinspection JSUnusedGlobalSymbols
  Mono = 0,
  Stereo = 1,
}
export enum Mode {
  // noinspection JSUnusedGlobalSymbols
  Normal = 0,
  PingPong = 1,
}
export enum LengthUnit {
  // noinspection JSUnusedGlobalSymbols
  LineDiv_128 = 0,
  Line = 1,
  LineDiv_2 = 2,
  LineDiv_3 = 3,
  Tick = 4,
  Ms = 5,
  Hz = 6,
}
export enum OnNoteOn {
  // noinspection JSUnusedGlobalSymbols
  Restart = 0,
  RestartCurrentIteration = 1,
}
