/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ModuleConstructor } from "./moduleBase"
import { Adsr } from "./adsr"
import { Amplifier } from "./amplifier"
import { AnalogGenerator } from "./analogGenerator"
import { Ctl2Note } from "./ctl2Note"
import { Compressor } from "./compressor"
import { DcBlocker } from "./dcBlocker"
import { Delay } from "./delay"
import { Distortion } from "./distortion"
import { DrumSynth } from "./drumSynth"
import { Echo } from "./echo"
import { Eq } from "./eq"
import { Feedback } from "./feedback"
import { Fft } from "./fft"
import { Filter } from "./filter"
import { FilterPro } from "./filterPro"
import { Flanger } from "./flanger"
import { Fm } from "./fm"
import { Fmx } from "./fmx"
import { Generator } from "./generator"
import { Glide } from "./glide"
import { Gpio } from "./gpio"
import { Input } from "./input"
import { Kicker } from "./kicker"
import { Lfo } from "./lfo"
import { Loop } from "./loop"
import { MetaModule } from "./metaModule"
import { Modulator } from "./modulator"
import { MultiCtl } from "./multiCtl"
import { MultiSynth } from "./multiSynth"
import { Output } from "./output"
import { Pitch2Ctl } from "./pitch2Ctl"
import { PitchDetector } from "./pitchDetector"
import { PitchShifter } from "./pitchShifter"
import { Reverb } from "./reverb"
import { Sampler } from "./sampler"
import { Smooth } from "./smooth"
import { Sound2Ctl } from "./sound2Ctl"
import { SpectraVoice } from "./spectraVoice"
import { Velocity2Ctl } from "./velocity2Ctl"
import { Vibrato } from "./vibrato"
import { VocalFilter } from "./vocalFilter"
import { VorbisPlayer } from "./vorbisPlayer"
import { WaveShaper } from "./waveShaper"
export { Adsr }
export { Amplifier }
export { AnalogGenerator }
export { Ctl2Note }
export { Compressor }
export { DcBlocker }
export { Delay }
export { Distortion }
export { DrumSynth }
export { Echo }
export { Eq }
export { Feedback }
export { Fft }
export { Filter }
export { FilterPro }
export { Flanger }
export { Fm }
export { Fmx }
export { Generator }
export { Glide }
export { Gpio }
export { Input }
export { Kicker }
export { Lfo }
export { Loop }
export { MetaModule }
export { Modulator }
export { MultiCtl }
export { MultiSynth }
export { Output }
export { Pitch2Ctl }
export { PitchDetector }
export { PitchShifter }
export { Reverb }
export { Sampler }
export { Smooth }
export { Sound2Ctl }
export { SpectraVoice }
export { Velocity2Ctl }
export { Vibrato }
export { VocalFilter }
export { VorbisPlayer }
export { WaveShaper }
// noinspection JSUnusedGlobalSymbols
export const adsr = () => new Adsr.Module()
// noinspection JSUnusedGlobalSymbols
export const amplifier = () => new Amplifier.Module()
// noinspection JSUnusedGlobalSymbols
export const analogGenerator = () => new AnalogGenerator.Module()
// noinspection JSUnusedGlobalSymbols
export const ctl2Note = () => new Ctl2Note.Module()
// noinspection JSUnusedGlobalSymbols
export const compressor = () => new Compressor.Module()
// noinspection JSUnusedGlobalSymbols
export const dcBlocker = () => new DcBlocker.Module()
// noinspection JSUnusedGlobalSymbols
export const delay = () => new Delay.Module()
// noinspection JSUnusedGlobalSymbols
export const distortion = () => new Distortion.Module()
// noinspection JSUnusedGlobalSymbols
export const drumSynth = () => new DrumSynth.Module()
// noinspection JSUnusedGlobalSymbols
export const echo = () => new Echo.Module()
// noinspection JSUnusedGlobalSymbols
export const eq = () => new Eq.Module()
// noinspection JSUnusedGlobalSymbols
export const feedback = () => new Feedback.Module()
// noinspection JSUnusedGlobalSymbols
export const fft = () => new Fft.Module()
// noinspection JSUnusedGlobalSymbols
export const filter = () => new Filter.Module()
// noinspection JSUnusedGlobalSymbols
export const filterPro = () => new FilterPro.Module()
// noinspection JSUnusedGlobalSymbols
export const flanger = () => new Flanger.Module()
// noinspection JSUnusedGlobalSymbols
export const fm = () => new Fm.Module()
// noinspection JSUnusedGlobalSymbols
export const fmx = () => new Fmx.Module()
// noinspection JSUnusedGlobalSymbols
export const generator = () => new Generator.Module()
// noinspection JSUnusedGlobalSymbols
export const glide = () => new Glide.Module()
// noinspection JSUnusedGlobalSymbols
export const gpio = () => new Gpio.Module()
// noinspection JSUnusedGlobalSymbols
export const input = () => new Input.Module()
// noinspection JSUnusedGlobalSymbols
export const kicker = () => new Kicker.Module()
// noinspection JSUnusedGlobalSymbols
export const lfo = () => new Lfo.Module()
// noinspection JSUnusedGlobalSymbols
export const loop = () => new Loop.Module()
// noinspection JSUnusedGlobalSymbols
export const metaModule = () => new MetaModule.Module()
// noinspection JSUnusedGlobalSymbols
export const modulator = () => new Modulator.Module()
// noinspection JSUnusedGlobalSymbols
export const multiCtl = () => new MultiCtl.Module()
// noinspection JSUnusedGlobalSymbols
export const multiSynth = () => new MultiSynth.Module()
// noinspection JSUnusedGlobalSymbols
export const output = () => new Output.Module()
// noinspection JSUnusedGlobalSymbols
export const pitch2Ctl = () => new Pitch2Ctl.Module()
// noinspection JSUnusedGlobalSymbols
export const pitchDetector = () => new PitchDetector.Module()
// noinspection JSUnusedGlobalSymbols
export const pitchShifter = () => new PitchShifter.Module()
// noinspection JSUnusedGlobalSymbols
export const reverb = () => new Reverb.Module()
// noinspection JSUnusedGlobalSymbols
export const sampler = () => new Sampler.Module()
// noinspection JSUnusedGlobalSymbols
export const smooth = () => new Smooth.Module()
// noinspection JSUnusedGlobalSymbols
export const sound2Ctl = () => new Sound2Ctl.Module()
// noinspection JSUnusedGlobalSymbols
export const spectraVoice = () => new SpectraVoice.Module()
// noinspection JSUnusedGlobalSymbols
export const velocity2Ctl = () => new Velocity2Ctl.Module()
// noinspection JSUnusedGlobalSymbols
export const vibrato = () => new Vibrato.Module()
// noinspection JSUnusedGlobalSymbols
export const vocalFilter = () => new VocalFilter.Module()
// noinspection JSUnusedGlobalSymbols
export const vorbisPlayer = () => new VorbisPlayer.Module()
// noinspection JSUnusedGlobalSymbols
export const waveShaper = () => new WaveShaper.Module()
export const moduleTypesByName: Record<string, ModuleConstructor> = {
  ADSR: Adsr.Module,
  Amplifier: Amplifier.Module,
  "Analog generator": AnalogGenerator.Module,
  Ctl2Note: Ctl2Note.Module,
  Compressor: Compressor.Module,
  "DC Blocker": DcBlocker.Module,
  Delay: Delay.Module,
  Distortion: Distortion.Module,
  DrumSynth: DrumSynth.Module,
  Echo: Echo.Module,
  EQ: Eq.Module,
  Feedback: Feedback.Module,
  FFT: Fft.Module,
  Filter: Filter.Module,
  "Filter Pro": FilterPro.Module,
  Flanger: Flanger.Module,
  FM: Fm.Module,
  FMX: Fmx.Module,
  Generator: Generator.Module,
  Glide: Glide.Module,
  GPIO: Gpio.Module,
  Input: Input.Module,
  Kicker: Kicker.Module,
  LFO: Lfo.Module,
  Loop: Loop.Module,
  MetaModule: MetaModule.Module,
  Modulator: Modulator.Module,
  MultiCtl: MultiCtl.Module,
  MultiSynth: MultiSynth.Module,
  Output: Output.Module,
  Pitch2Ctl: Pitch2Ctl.Module,
  "Pitch Detector": PitchDetector.Module,
  "Pitch shifter": PitchShifter.Module,
  Reverb: Reverb.Module,
  Sampler: Sampler.Module,
  Smooth: Smooth.Module,
  Sound2Ctl: Sound2Ctl.Module,
  SpectraVoice: SpectraVoice.Module,
  Velocity2Ctl: Velocity2Ctl.Module,
  Vibrato: Vibrato.Module,
  "Vocal filter": VocalFilter.Module,
  "Vorbis player": VorbisPlayer.Module,
  WaveShaper: WaveShaper.Module,
}
