/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
export enum PlayPatterns {
  // noinspection JSUnusedGlobalSymbols
  Off = 0,
  On = 1,
  OnNoRepeat = 2,
}
