/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
export interface MetaModuleControllerValues extends ControllerValues {
  volume: number
  inputModule: number
  playPatterns: PlayPatterns
  bpm: number
  tpl: number
}
