/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
// Intentionally duplicated enums - see also modulator.ts
// (TypeScript does not allow exporting imported enums from inside a namespace)
export enum ModulationType {
  // noinspection JSUnusedGlobalSymbols
  Amplitude = 0,
  Phase = 1,
  PhaseAbs = 2,
}
export enum Channels {
  // noinspection JSUnusedGlobalSymbols
  Stereo = 0,
  Mono = 1,
}
