/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { Controllers, ModuleType } from "./moduleType"
import { ModulatorControllerValues } from "./modulatorControllerValues"
// @ts-ignore
// noinspection ES6UnusedImports
import { ModulationType } from "./modulatorEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { Channels } from "./modulatorEnums"
export class ModulatorBaseControllers implements Controllers {
  constructor(
    readonly module: ModuleType,
    readonly controllerValues: ModulatorControllerValues
  ) {}
  // noinspection JSUnusedGlobalSymbols
  get volume(): number {
    return this.controllerValues.volume
  }
  // noinspection JSUnusedGlobalSymbols
  set volume(newValue: number) {
    const { controllerValues } = this
    newValue = Math.min(Math.max(newValue, 0), 512)
    controllerValues.volume = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get modulationType(): ModulationType {
    return this.controllerValues.modulationType
  }
  // noinspection JSUnusedGlobalSymbols
  set modulationType(newValue: ModulationType) {
    const { controllerValues } = this
    controllerValues.modulationType = newValue
  }
  // noinspection JSUnusedGlobalSymbols
  get channels(): Channels {
    return this.controllerValues.channels
  }
  // noinspection JSUnusedGlobalSymbols
  set channels(newValue: Channels) {
    const { controllerValues } = this
    controllerValues.channels = newValue
  }
}
