/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
// @ts-ignore
// noinspection ES6UnusedImports
import { ActiveCurve } from "./multiSynthEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { OutPortMode } from "./multiSynthEnums"
export interface MultiSynthControllerValues extends ControllerValues {
  transpose: number
  randomPitch: number
  velocity: number
  finetune: number
  randomPhase: number
  randomVelocity: number
  phase: number
  curve2Influence: number
}
