/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
// Intentionally duplicated enums - see also multiSynth.ts
// (TypeScript does not allow exporting imported enums from inside a namespace)
export enum ActiveCurve {
  // noinspection JSUnusedGlobalSymbols
  NoteVelocity = 0,
  VelocityVelocity = 1,
  NotePitch = 2,
}
export enum OutPortMode {
  // noinspection JSUnusedGlobalSymbols
  AllOrRandom1 = 0,
  NoteModNumOfOutsOrRandom2 = 1,
  PolyChModNumOfOutsOrRandom3 = 2,
  Cyclic = 3,
}
