/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
// Intentionally duplicated enums - see also pitchDetector.ts
// (TypeScript does not allow exporting imported enums from inside a namespace)
export enum Algorithm {
  // noinspection JSUnusedGlobalSymbols
  ZeroCrossing = 0,
  Autocorrelation = 1,
  Cepstrum = 2,
}
export enum RollOff {
  // noinspection JSUnusedGlobalSymbols
  Db_12 = 0,
  Db_24 = 1,
  Db_36 = 2,
  Db_48 = 3,
}
export enum SampleRate {
  // noinspection JSUnusedGlobalSymbols
  Hz_12 = 0,
  Hz_24 = 1,
  Hz_44 = 2,
}
export enum Buffer {
  // noinspection JSUnusedGlobalSymbols
  Ms_5m = 0,
  Ms_10 = 1,
  Ms_21 = 2,
  Ms_42 = 3,
  Ms_85 = 4,
}
