/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
// @ts-ignore
// noinspection ES6UnusedImports
import { Mode } from "./reverbEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { AllPassFilter } from "./reverbEnums"
export interface ReverbControllerValues extends ControllerValues {
  dry: number
  wet: number
  feedback: number
  damp: number
  stereoWidth: number
  freeze: boolean
  mode: Mode
  allPassFilter: AllPassFilter
  roomSize: number
  randomSeed: number
}
