/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
export enum SampleInterpolation {
  // noinspection JSUnusedGlobalSymbols
  Off = 0,
  Linear = 1,
  Spline = 2,
}
export enum EnvelopeInterpolation {
  // noinspection JSUnusedGlobalSymbols
  Off = 0,
  Linear = 1,
}
export enum VibratoType {
  // noinspection JSUnusedGlobalSymbols
  Sin = 0,
  Saw = 1,
  Square = 2,
}
export enum LoopType {
  // noinspection JSUnusedGlobalSymbols
  Off = 0,
  Forward = 1,
  PingPong = 2,
}
export enum Format {
  // noinspection JSUnusedGlobalSymbols
  Int8 = 1,
  Int16 = 2,
  Float32 = 4,
}
export enum Channels {
  // noinspection JSUnusedGlobalSymbols
  Mono = 0,
  Stereo = 8,
}
