/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
export interface SamplerControllerValues extends ControllerValues {
  volume: number
  panning: number
  sampleInterpolation: SampleInterpolation
  envelopeInterpolation: EnvelopeInterpolation
  polyphonyCh: number
  recThreshold: number
  vibratoType: VibratoType
  vibratoAttack: number
  vibratoDepth: number
  vibratoRate: number
  volumeFadeout: number
}
