/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
// @ts-ignore
// noinspection ES6UnusedImports
import { Mode } from "./smoothEnums"
// @ts-ignore
// noinspection ES6UnusedImports
import { Channels } from "./smoothEnums"
export interface SmoothControllerValues extends ControllerValues {
  rise: number
  fall: number
  fallEqRise: boolean
  scale: number
  mode: Mode
  channels: Channels
}
