/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
// Intentionally duplicated enums - see also spectraVoice.ts
// (TypeScript does not allow exporting imported enums from inside a namespace)
export enum Mode {
  // noinspection JSUnusedGlobalSymbols
  Hq = 0,
  HqMono = 1,
  Lq = 2,
  LqMono = 3,
  HqSpline = 4,
}
export enum HarmonicType {
  // noinspection JSUnusedGlobalSymbols
  Hsin = 0,
  Rect = 1,
  Org1 = 2,
  Org2 = 3,
  Org3 = 4,
  Org4 = 5,
  Sin = 6,
  Random = 7,
  Triangle1 = 8,
  Triangle2 = 9,
  Overtones1 = 10,
  Overtones2 = 11,
  Overtones3 = 12,
  Overtones4 = 13,
  Overtones1Plus_ = 14,
  Overtones2Plus_ = 15,
  Overtones3Plus_ = 16,
  Overtones4Plus_ = 17,
  Metal = 18,
}
