/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
export enum Mode {
  // noinspection JSUnusedGlobalSymbols
  Hq = 0,
  HqMono = 1,
  Lq = 2,
  LqMono = 3,
  HqSpline = 4,
}
export enum HarmonicType {
  // noinspection JSUnusedGlobalSymbols
  Hsin = 0,
  Rect = 1,
  Org1 = 2,
  Org2 = 3,
  Org3 = 4,
  Org4 = 5,
  Sin = 6,
  Random = 7,
  Triangle1 = 8,
  Triangle2 = 9,
  Overtones1 = 10,
  Overtones2 = 11,
  Overtones3 = 12,
  Overtones4 = 13,
}
