/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { MidiMap, ControllerMidiMap, ControllerMidiMaps } from "../controllerMidiMap"
import { Project } from "../project"
import { ModuleBase } from "./moduleBase"
import { ModuleType, OptionValues, Options } from "./moduleType"
import { SpectraVoiceBehavior } from "./spectraVoiceBehavior"
import { SpectraVoiceControllers } from "./spectraVoiceControllers"
import { SpectraVoiceControllerValues } from "./spectraVoiceControllerValues"
import { Mode as _Mode } from "./spectraVoiceEnums"
import { HarmonicType as _HarmonicType } from "./spectraVoiceEnums"
export namespace SpectraVoice {
  export const Mode = _Mode
  export const HarmonicType = _HarmonicType
  interface SpectraVoiceControllerMidiMaps extends ControllerMidiMaps {
    volume: ControllerMidiMap
    panning: ControllerMidiMap
    attack: ControllerMidiMap
    release: ControllerMidiMap
    polyphonyCh: ControllerMidiMap
    mode: ControllerMidiMap
    sustain: ControllerMidiMap
    spectrumResolution: ControllerMidiMap
    harmonic: ControllerMidiMap
    hFreqHz: ControllerMidiMap
    hVolume: ControllerMidiMap
    hWidth: ControllerMidiMap
    hType: ControllerMidiMap
  }
  interface SpectraVoiceOptionValues extends OptionValues {}
  class SpectraVoiceOptions implements Options {
    constructor(readonly optionValues: SpectraVoiceOptionValues) {}
  }
  export class Module extends ModuleBase implements ModuleType {
    name = "SpectraVoice"
    flags = 73
    readonly typeName = "SpectraVoice"
    readonly controllerSetters = [
      (val: number) => {
        this.controllerValues.volume = val
      },
      (val: number) => {
        this.controllerValues.panning = val
      },
      (val: number) => {
        this.controllerValues.attack = val
      },
      (val: number) => {
        this.controllerValues.release = val
      },
      (val: number) => {
        this.controllerValues.polyphonyCh = val
      },
      (val: number) => {
        this.controllerValues.mode = val
      },
      (val: number) => {
        this.controllerValues.sustain = Boolean(val)
      },
      (val: number) => {
        this.controllerValues.spectrumResolution = val
      },
      (val: number) => {
        this.controllerValues.harmonic = val
      },
      (val: number) => {
        this.controllerValues.hFreqHz = val
      },
      (val: number) => {
        this.controllerValues.hVolume = val
      },
      (val: number) => {
        this.controllerValues.hWidth = val
      },
      (val: number) => {
        this.controllerValues.hType = val
      },
    ]
    readonly controllerValues: SpectraVoiceControllerValues = {
      volume: 128,
      panning: 0,
      attack: 10,
      release: 512,
      polyphonyCh: 8,
      mode: Mode.HqSpline,
      sustain: true,
      spectrumResolution: 1,
      harmonic: 0,
      hFreqHz: 1098,
      hVolume: 255,
      hWidth: 3,
      hType: HarmonicType.Hsin,
    }
    readonly controllers: SpectraVoiceControllers = new SpectraVoiceControllers(
      this,
      this.controllerValues
    )
    readonly c = this.controllers
    readonly midiMaps: SpectraVoiceControllerMidiMaps = {
      volume: new ControllerMidiMap(),
      panning: new ControllerMidiMap(),
      attack: new ControllerMidiMap(),
      release: new ControllerMidiMap(),
      polyphonyCh: new ControllerMidiMap(),
      mode: new ControllerMidiMap(),
      sustain: new ControllerMidiMap(),
      spectrumResolution: new ControllerMidiMap(),
      harmonic: new ControllerMidiMap(),
      hFreqHz: new ControllerMidiMap(),
      hVolume: new ControllerMidiMap(),
      hWidth: new ControllerMidiMap(),
      hType: new ControllerMidiMap(),
    }
    readonly optionValues: SpectraVoiceOptionValues = {}
    readonly options: SpectraVoiceOptions = new SpectraVoiceOptions(this.optionValues)
    readonly o = this.options
    behavior?: SpectraVoiceBehavior
    constructor() {
      super()
      this.behavior = new SpectraVoiceBehavior(this)
    }
    attachTo(project: Project): AttachedModule {
      return super.attachTo(project) as AttachedModule
    }
    *rawControllerValues(): Generator<number> {
      const { controllerValues: cv } = this
      yield cv.volume
      yield cv.panning
      yield cv.attack
      yield cv.release
      yield cv.polyphonyCh
      yield cv.mode
      yield Number(cv.sustain)
      yield cv.spectrumResolution
      yield cv.harmonic
      yield cv.hFreqHz
      yield cv.hVolume
      yield cv.hWidth
      yield cv.hType
    }
    setMidiMaps(midiMaps: MidiMap[]) {
      this.midiMaps.volume = midiMaps[0]
      this.midiMaps.panning = midiMaps[1]
      this.midiMaps.attack = midiMaps[2]
      this.midiMaps.release = midiMaps[3]
      this.midiMaps.polyphonyCh = midiMaps[4]
      this.midiMaps.mode = midiMaps[5]
      this.midiMaps.sustain = midiMaps[6]
      this.midiMaps.spectrumResolution = midiMaps[7]
      this.midiMaps.harmonic = midiMaps[8]
      this.midiMaps.hFreqHz = midiMaps[9]
      this.midiMaps.hVolume = midiMaps[10]
      this.midiMaps.hWidth = midiMaps[11]
      this.midiMaps.hType = midiMaps[12]
    }
    midiMapsArray(): MidiMap[] {
      const a: MidiMap[] = []
      a.push(this.midiMaps.volume)
      a.push(this.midiMaps.panning)
      a.push(this.midiMaps.attack)
      a.push(this.midiMaps.release)
      a.push(this.midiMaps.polyphonyCh)
      a.push(this.midiMaps.mode)
      a.push(this.midiMaps.sustain)
      a.push(this.midiMaps.spectrumResolution)
      a.push(this.midiMaps.harmonic)
      a.push(this.midiMaps.hFreqHz)
      a.push(this.midiMaps.hVolume)
      a.push(this.midiMaps.hWidth)
      a.push(this.midiMaps.hType)
      return a
    }
  }
  export class AttachedModule extends Module {
    get index(): number {
      if (this._index === undefined) {
        throw new Error("Attached module has empty index")
      }
      return this._index
    }
    set index(_: number) {
      throw new Error("Module index can only be assigned once")
    }
  }
}
