/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
export interface Velocity2CtlControllerValues extends ControllerValues {
  noteOffAction: NoteOffAction
  outMin: number
  outMax: number
  outOffset: number
  outController: number
}
