/**
 * -- DO NOT EDIT THIS FILE DIRECTLY --
 *
 * This file was auto-generated by genrv.
 */
import { ControllerValues } from "./moduleType"
export interface WaveShaperControllerValues extends ControllerValues {
  inputVolume: number
  mix: number
  outputVolume: number
  symmetric: boolean
  mode: Mode
  dcBlocker: boolean
}
