name: pre-commit-all
on:
  - push
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files
